-- VUA Trading Agent — TASK-P0-002 Corrective Migration (FAILED)
-- This migration was generated by Prisma 7.10.0 and FAILED to apply.
-- Preserved as forensic evidence.
--
-- Error:
-- ERROR: foreign key constraint "fill_events_order_id_fkey" cannot be implemented
-- DETAIL: Key columns "order_id" and "id" are of incompatible types: uuid and text.
--
-- Root cause:
-- The canonical schema mixed String @id @default(uuid()) without @db.Uuid
-- with explicit @db.Uuid annotations on FK columns, causing Prisma 7 to
-- generate an internally inconsistent migration.

-- CreateTable
CREATE TABLE "system_config" (
    "id" TEXT NOT NULL,
    "schema_version" INTEGER NOT NULL DEFAULT 1,
    "mode" TEXT NOT NULL DEFAULT 'PAPER',
    "selected_exchange" TEXT NOT NULL DEFAULT 'BINANCE',
    "selected_symbol" TEXT NOT NULL DEFAULT 'BTC/USDT',
    "initial_capital_usd" DECIMAL(18,4) NOT NULL DEFAULT 10000,
    "current_equity_usd" DECIMAL(18,4) NOT NULL DEFAULT 10000,
    "daily_start_equity_usd" DECIMAL(18,4) NOT NULL DEFAULT 10000,
    "high_water_mark_usd" DECIMAL(18,4) NOT NULL DEFAULT 10000,
    "max_drawdown_percent" DECIMAL(8,4) NOT NULL DEFAULT 3.0,
    "autonomous_cycle_seconds" INTEGER NOT NULL DEFAULT 12,
    "auto_trading_enabled" BOOLEAN NOT NULL DEFAULT false,
    "engine_running" BOOLEAN NOT NULL DEFAULT false,
    "kill_switch_engaged" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "system_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "config_history" (
    "id" TEXT NOT NULL,
    "config_type" TEXT NOT NULL,
    "previous_config_json" JSONB NOT NULL,
    "new_config_json" JSONB NOT NULL,
    "changed_by" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "config_history_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "decisions" (
    "id" UUID NOT NULL,
    "snapshot_hash" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "exchange" TEXT NOT NULL,
    "regime_at_decision" TEXT NOT NULL,
    "regime_confidence" DECIMAL(6,4) NOT NULL,
    "trend_direction" TEXT,
    "volatility_state" TEXT,
    "macro_analyst_verdict" TEXT NOT NULL,
    "technical_strategist_verdict" TEXT NOT NULL,
    "contrarian_skeptic_verdict" TEXT NOT NULL,
    "risk_officer_verdict" TEXT NOT NULL,
    "cio_synthesizer_verdict" TEXT NOT NULL,
    "cio_final_verdict" TEXT NOT NULL,
    "confidence_score" DECIMAL(6,4) NOT NULL,
    "edge_probability" DECIMAL(6,4) NOT NULL,
    "synthesis_rationale" TEXT NOT NULL,
    "trade_hypothesis_json" JSONB,
    "engine_mode" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "decisions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "orders" (
    "id" TEXT NOT NULL,
    "client_order_id" TEXT NOT NULL,
    "exchange_order_id" TEXT,
    "decision_id" UUID,
    "symbol" TEXT NOT NULL,
    "exchange" TEXT NOT NULL,
    "side" TEXT NOT NULL,
    "order_type" TEXT NOT NULL DEFAULT 'MARKET',
    "price" DECIMAL(20,8) NOT NULL,
    "quantity" DECIMAL(24,8) NOT NULL,
    "cost_usd" DECIMAL(18,4) NOT NULL,
    "leverage" DECIMAL(8,2) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'SUBMITTED',
    "filled_quantity" DECIMAL(24,8) NOT NULL DEFAULT 0,
    "avg_fill_price" DECIMAL(20,8),
    "total_fee_usd" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "slippage_percent" DECIMAL(8,4) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "acknowledged_at" TIMESTAMP(3),
    "filled_at" TIMESTAMP(3),
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "fill_events" (
    "id" TEXT NOT NULL,
    "order_id" UUID NOT NULL,
    "exchange_fill_id" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "exchange" TEXT NOT NULL,
    "side" TEXT NOT NULL,
    "fill_quantity" DECIMAL(24,8) NOT NULL,
    "fill_price" DECIMAL(20,8) NOT NULL,
    "fee_usd" DECIMAL(18,4) NOT NULL,
    "fee_rate" DECIMAL(8,6) NOT NULL,
    "liquidity" TEXT,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "event_sequence" INTEGER NOT NULL,

    CONSTRAINT "fill_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "positions" (
    "id" TEXT NOT NULL,
    "originating_order_id" UUID NOT NULL,
    "symbol" TEXT NOT NULL,
    "exchange" TEXT NOT NULL,
    "side" TEXT NOT NULL,
    "entry_price" DECIMAL(20,8) NOT NULL,
    "current_price" DECIMAL(20,8),
    "quantity" DECIMAL(24,8) NOT NULL,
    "initial_quantity" DECIMAL(24,8) NOT NULL,
    "leverage" DECIMAL(8,2) NOT NULL,
    "initial_margin_usd" DECIMAL(18,4) NOT NULL,
    "unrealized_pnl_usd" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "unrealized_pnl_percent" DECIMAL(8,4) NOT NULL DEFAULT 0,
    "stop_loss_price" DECIMAL(20,8) NOT NULL,
    "trailing_stop_price" DECIMAL(20,8),
    "take_profit_1_price" DECIMAL(20,8) NOT NULL,
    "take_profit_2_price" DECIMAL(20,8) NOT NULL,
    "take_profit_3_price" DECIMAL(20,8) NOT NULL,
    "liquidation_price" DECIMAL(20,8) NOT NULL,
    "realized_pnl_usd" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'OPEN',
    "close_reason" TEXT,
    "opened_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "closed_at" TIMESTAMP(3),
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "positions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "position_events" (
    "id" TEXT NOT NULL,
    "position_id" UUID NOT NULL,
    "event_type" TEXT NOT NULL,
    "price" DECIMAL(20,8) NOT NULL,
    "quantity" DECIMAL(24,8) NOT NULL,
    "unrealized_pnl_usd" DECIMAL(18,4) NOT NULL,
    "realized_pnl_usd" DECIMAL(18,4),
    "fee_usd" DECIMAL(18,4),
    "metadata_json" JSONB,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "event_sequence" INTEGER NOT NULL,

    CONSTRAINT "position_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "risk_decisions" (
    "id" TEXT NOT NULL,
    "decision_id" UUID,
    "order_id" UUID,
    "symbol" TEXT NOT NULL,
    "exchange" TEXT NOT NULL,
    "approved" BOOLEAN NOT NULL,
    "veto_reason" TEXT,
    "checks_passed_json" JSONB NOT NULL,
    "max_allowed_risk_usd" DECIMAL(18,4) NOT NULL,
    "recommended_position_size_usd" DECIMAL(18,4) NOT NULL,
    "recommended_leverage" DECIMAL(8,2) NOT NULL,
    "estimated_liquidation_price" DECIMAL(20,8) NOT NULL,
    "kelly_fraction" DECIMAL(8,4) NOT NULL,
    "circuit_breaker_status" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "risk_decisions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reconciliation_events" (
    "id" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "exchange" TEXT NOT NULL,
    "event_type" TEXT NOT NULL,
    "db_state_json" JSONB NOT NULL,
    "exchange_state_json" JSONB NOT NULL,
    "discrepancy_description" TEXT NOT NULL,
    "resolution_action" TEXT,
    "severity" TEXT NOT NULL DEFAULT 'INFO',
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "reconciliation_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "system_events" (
    "id" TEXT NOT NULL,
    "event_type" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "severity" TEXT NOT NULL DEFAULT 'INFO',
    "metadata_json" JSONB,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "system_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "market_data_candles" (
    "id" BIGSERIAL NOT NULL,
    "symbol" TEXT NOT NULL,
    "exchange" TEXT NOT NULL,
    "interval" TEXT NOT NULL,
    "open" DECIMAL(20,8) NOT NULL,
    "high" DECIMAL(20,8) NOT NULL,
    "low" DECIMAL(20,8) NOT NULL,
    "close" DECIMAL(20,8) NOT NULL,
    "volume" DECIMAL(24,8) NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL,
    "ingested_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "market_data_candles_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "config_history_config_type_timestamp_idx" ON "config_history"("config_type", "timestamp");

-- CreateIndex
CREATE INDEX "decisions_symbol_exchange_created_at_idx" ON "decisions"("symbol", "exchange", "created_at");

-- CreateIndex
CREATE INDEX "decisions_cio_final_verdict_created_at_idx" ON "decisions"("cio_final_verdict", "created_at");

-- CreateIndex
CREATE INDEX "orders_symbol_exchange_status_idx" ON "orders"("symbol", "exchange", "status");

-- CreateIndex
CREATE INDEX "orders_status_created_at_idx" ON "orders"("status", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "orders_client_order_id_exchange_symbol_key" ON "orders"("client_order_id", "exchange", "symbol");

-- CreateIndex
CREATE INDEX "fill_events_order_id_event_sequence_idx" ON "fill_events"("order_id", "event_sequence");

-- CreateIndex
CREATE INDEX "fill_events_timestamp_idx" ON "fill_events"("timestamp");

-- CreateIndex
CREATE UNIQUE INDEX "fill_events_exchange_fill_id_symbol_timestamp_key" ON "fill_events"("exchange_fill_id", "symbol", "timestamp");

-- CreateIndex
CREATE INDEX "positions_symbol_exchange_status_idx" ON "positions"("symbol", "exchange", "status");

-- CreateIndex
CREATE INDEX "positions_status_opened_at_idx" ON "positions"("status", "opened_at");

-- CreateIndex
CREATE INDEX "position_events_position_id_timestamp_idx" ON "position_events"("position_id", "timestamp");

-- CreateIndex
CREATE INDEX "position_events_event_type_timestamp_idx" ON "position_events"("event_type", "timestamp");

-- CreateIndex
CREATE UNIQUE INDEX "position_events_position_id_event_sequence_key" ON "position_events"("position_id", "event_sequence");

-- CreateIndex
CREATE UNIQUE INDEX "risk_decisions_decision_id_key" ON "risk_decisions"("decision_id");

-- CreateIndex
CREATE INDEX "risk_decisions_symbol_exchange_timestamp_idx" ON "risk_decisions"("symbol", "exchange", "timestamp");

-- CreateIndex
CREATE INDEX "risk_decisions_approved_timestamp_idx" ON "risk_decisions"("approved", "timestamp");

-- CreateIndex
CREATE INDEX "reconciliation_events_symbol_exchange_timestamp_idx" ON "reconciliation_events"("symbol", "exchange", "timestamp");

-- CreateIndex
CREATE INDEX "reconciliation_events_event_type_timestamp_idx" ON "reconciliation_events"("event_type", "timestamp");

-- CreateIndex
CREATE INDEX "reconciliation_events_severity_timestamp_idx" ON "reconciliation_events"("severity", "timestamp");

-- CreateIndex
CREATE INDEX "system_events_event_type_timestamp_idx" ON "system_events"("event_type", "timestamp");

-- CreateIndex
CREATE INDEX "system_events_severity_timestamp_idx" ON "system_events"("severity", "timestamp");

-- CreateIndex
CREATE INDEX "market_data_candles_symbol_exchange_interval_timestamp_idx" ON "market_data_candles"("symbol", "exchange", "interval", "timestamp");

-- CreateIndex
CREATE UNIQUE INDEX "market_data_candles_symbol_exchange_interval_timestamp_key" ON "market_data_candles"("symbol", "exchange", "interval", "timestamp");

-- AddForeignKey
ALTER TABLE "orders" ADD CONSTRAINT "orders_decision_id_fkey" FOREIGN KEY ("decision_id") REFERENCES "decisions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "fill_events" ADD CONSTRAINT "fill_events_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "positions" ADD CONSTRAINT "positions_originating_order_id_fkey" FOREIGN KEY ("originating_order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "position_events" ADD CONSTRAINT "position_events_position_id_fkey" FOREIGN KEY ("position_id") REFERENCES "positions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "risk_decisions" ADD CONSTRAINT "risk_decisions_decision_id_fkey" FOREIGN KEY ("decision_id") REFERENCES "decisions"("id") ON DELETE SET NULL ON UPDATE CASCADE;
